# Generated by Django 5.0.6 on 2024-12-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
